import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-theme="dark"
    >
      <body className="min-h-full flex flex-col bg-(--background) selection:bg-accent/30 selection:text-accent">
        {/* Subtle Background Noise/Grain for texture */}
        <div className="fixed inset-0 pointer-events-none opacity-3 mix-blend-overlay z-[-1]" style={{ backgroundImage: 'url("https://grainy-gradients.vercel.app/noise.svg")' }}></div>
        
        <Navbar />
        <main className="flex-1 max-w-7xl w-full mx-auto px-6 sm:px-10 lg:px-12 py-12 md:py-16">
          {children}
        </main>
        
        <footer className="py-12 border-t border-(--border) mt-auto">
          <div className="max-w-7xl mx-auto px-6 text-center">
            <p className="text-[10px] text-(--muted-foreground) font-black uppercase tracking-[0.4em]">
              Grand & Grey &copy; 2026 &mdash; Internal Financial Systems
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
